-- MySQL Script generated by MySQL Workbench
-- Mon Mar 24 15:54:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dietas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dietas` ;

-- -----------------------------------------------------
-- Schema dietas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dietas` DEFAULT CHARACTER SET utf8 COLLATE utf8_swedish_ci ;
USE `dietas` ;

-- -----------------------------------------------------
-- Table `dietas`.`Alergias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dietas`.`Alergias` ;

CREATE TABLE IF NOT EXISTS `dietas`.`Alergias` (
                                                   `id_alergia` VARCHAR(5) NOT NULL,
    `nombre_alergia` VARCHAR(45) NOT NULL,
    `id_usuario` INT NOT NULL,
    PRIMARY KEY (`id_alergia`, `id_usuario`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dietas`.`Alergias_Alimentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dietas`.`Alergias_Alimentos` ;

CREATE TABLE IF NOT EXISTS `dietas`.`Alergias_Alimentos` (
                                                             `id_alergia` VARCHAR(5) NOT NULL,
    `id_alimentos` VARCHAR(5) NOT NULL,
    `id_usuario` INT NOT NULL,
    PRIMARY KEY (`id_alergia`, `id_usuario`, `id_alimentos`),
    INDEX `fk_Alergias_has_Alimentos_Alimentos1_idx` (`id_alimentos` ASC),
    INDEX `fk_Alergias_has_Alimentos_Alergias1_idx` (`id_alergia` ASC),
    CONSTRAINT `fk_Alergias_has_Alimentos_Alergias1`
    FOREIGN KEY (`id_alergia`)
    REFERENCES `dietas`.`Alergias` (`id_alergia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Alergias_has_Alimentos_Alimentos1`
    FOREIGN KEY (`id_alimentos`)
    REFERENCES `dietas`.`Alimentos` (`id_alimentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dietas`.`Alimentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dietas`.`Alimentos` ;

CREATE TABLE IF NOT EXISTS `dietas`.`Alimentos` (
                                                    `id_alimentos` VARCHAR(5) NOT NULL,
    `nombreAlimento` VARCHAR(100) NOT NULL,
    `PC` FLOAT NOT NULL,
    `e_100` FLOAT NOT NULL,
    `prot_100` FLOAT NOT NULL,
    `grasa_100` FLOAT NOT NULL,
    `ags_100` FLOAT NOT NULL,
    `agmi_100` FLOAT NOT NULL,
    `agpi_100` FLOAT NOT NULL,
    `col_100` FLOAT NOT NULL,
    `hc_100` FLOAT NOT NULL,
    `fibra_100` FLOAT NOT NULL,
    `vit_c_100` FLOAT NOT NULL,
    `vit_b6_100` FLOAT NOT NULL,
    `vit_e_100` FLOAT NOT NULL,
    `fe_100` FLOAT NOT NULL,
    `na_100` FLOAT NOT NULL,
    `ca_100` FLOAT NOT NULL,
    `k_100` FLOAT NOT NULL,
    `vit_d_100` FLOAT NOT NULL,
    `pesoBruto` FLOAT NOT NULL,
    `id_usuario` INT NOT NULL,
    PRIMARY KEY (`id_alimentos`, `id_usuario`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dietas`.`Alimentos_Recetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dietas`.`Alimentos_Recetas` ;

CREATE TABLE IF NOT EXISTS `dietas`.`Alimentos_Recetas` (
                                                            `id_alimentos` VARCHAR(5) NOT NULL,
    `id_receta` VARCHAR(5) NOT NULL,
    `id_usuario` INT NOT NULL,
    PRIMARY KEY (`id_alimentos`, `id_receta`, `id_usuario`),
    INDEX `fk_Alimentos_has_Recetas_Recetas1_idx` (`id_receta` ASC),
    INDEX `fk_Alimentos_has_Recetas_Alimentos1_idx` (`id_alimentos` ASC),
    CONSTRAINT `fk_Alimentos_has_Recetas_Alimentos1`
    FOREIGN KEY (`id_alimentos`)
    REFERENCES `dietas`.`Alimentos` (`id_alimentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Alimentos_has_Recetas_Recetas1`
    FOREIGN KEY (`id_receta`)
    REFERENCES `dietas`.`Recetas` (`id_receta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dietas`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dietas`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `dietas`.`Clientes` (
                                                   `dni_cliente` VARCHAR(8) NOT NULL,
    `nombre` VARCHAR(30) NOT NULL,
    `apellido` VARCHAR(50) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`dni_cliente`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dietas`.`Clientes_Alergias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dietas`.`Clientes_Alergias` ;

CREATE TABLE IF NOT EXISTS `dietas`.`Clientes_Alergias` (
                                                            `dni_cliente` VARCHAR(8) NOT NULL,
    `id_alergia` VARCHAR(5) NOT NULL,
    `descripcion` VARCHAR(45) NULL,
    `id_usuario` INT NOT NULL,
    PRIMARY KEY (`dni_cliente`, `id_alergia`, `id_usuario`),
    INDEX `fk_Clientes_has_Alergias_Alergias1_idx` (`id_alergia` ASC),
    INDEX `fk_Clientes_has_Alergias_Clientes_idx` (`dni_cliente` ASC),
    CONSTRAINT `fk_Clientes_has_Alergias_Clientes`
    FOREIGN KEY (`dni_cliente`)
    REFERENCES `dietas`.`Clientes` (`dni_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Clientes_has_Alergias_Alergias1`
    FOREIGN KEY (`id_alergia`)
    REFERENCES `dietas`.`Alergias` (`id_alergia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dietas`.`Recetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dietas`.`Recetas` ;

CREATE TABLE IF NOT EXISTS `dietas`.`Recetas` (
                                                  `id_receta` VARCHAR(5) NOT NULL,
    `nombre_receta` VARCHAR(65) NOT NULL,
    `desc_receta` VARCHAR(150) NOT NULL,
    `id_usuario` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id_receta`, `id_usuario`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dietas`.`Recetas_Semana`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dietas`.`Recetas_Semana` ;

CREATE TABLE IF NOT EXISTS `dietas`.`Recetas_Semana` (
                                                         `diaSemana` ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO') NOT NULL,
    `momentoDia` ENUM('DESAYUNO', 'ALMUERZO', 'COMIDA', 'MERIENDA', 'CENA', 'SUPLEMENTO') NOT NULL,
    `id_receta` VARCHAR(5) NULL,
    `dni_cliente` VARCHAR(8) NOT NULL,
    `peso` FLOAT NULL,
    `id_usuario` INT NOT NULL,
    PRIMARY KEY (`diaSemana`, `momentoDia`, `id_receta`, `dni_cliente`, `id_usuario`),
    INDEX `fk_Recetas_Semana_Recetas1_idx` (`id_receta` ASC),
    INDEX `fk_Recetas_Semana_Clientes1_idx` (`dni_cliente` ASC),
    CONSTRAINT `fk_Recetas_Semana_Recetas1`
    FOREIGN KEY (`id_receta`)
    REFERENCES `dietas`.`Recetas` (`id_receta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Recetas_Semana_Clientes1`
    FOREIGN KEY (`dni_cliente`)
    REFERENCES `dietas`.`Clientes` (`dni_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dietas`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dietas`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `dietas`.`Usuarios` (
                                                   `id_usuarios` INT NOT NULL AUTO_INCREMENT,
                                                   `nombre` VARCHAR(30) NOT NULL,
    `apellidos` VARCHAR(50) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `contrasena` VARCHAR(25) NOT NULL,
    `administrador` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id_usuarios`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;